### ISSUE TITLE
Test case 21 fails with fast code

### ISSUE THREAD

**Issue by janavarun12** [danuzclaudes/COMP-550-AlgorithmAnalysis#1]
`
int maxHeight = 0;
root = -1;

```
        for (int j = 0; j < n; j++) {
            int currentHeight = 0, i = j;
            while (parent[i] != root) {
                i = parent[i];
                currentHeight++;
            }
            maxHeight = Math.max(maxHeight, currentHeight);
        }
        return maxHeight + 1;
```

`
Hello i could not pass test case 21 with the fast code.
Also is it not similar to the naive algorithm except you used a while loop.
[21.txt](https://github.com/danuzclaudes/COMP-550-AlgorithmAnalysis/files/450172/21.txt)

**Comment by MoraliProduktionstechnikGmbH** [comment]
Which Programming assignment / Problem?

**Comment by cho-zhang** [comment]
@MoraliProduktionstechnikGmbH: Data Structure course, Week 1, the assignment for Tree Height FYI.

**Comment by MoraliProduktionstechnikGmbH** [comment]
You can solve it using DP(Dynamic Programming), The following code fragment illustrates the fundamental idea:

```
int computeHeight() 
{
          int[] mem = new int[parent.length];
          int maxHeight = 0;
          for (int vertex = 0; vertex < n; vertex++)
          {
             int height = computeVertexHeight(vertex, parent, mem);
             maxHeight = Math.max(maxHeight, height);
          }
          return maxHeight;
}
```

I hope it will help

**Comment by cho-zhang** [comment]
@janavarun12 @MoraliProduktionstechnikGmbH, I have updated the code.

Here's the local running output and running time:

```
21: OK naive=100000 fast=100000 timing=4
22: OK naive=66649 fast=66649 timing=4
23: OK naive=33334 fast=33334 timing=1
24: OK naive=50001 fast=50001 timing=3
```

Please let me know if this will make OJ happy. Thank you both for your contribution! Cheers.

**Comment by MoraliProduktionstechnikGmbH** [comment]
What do you mean by OJ?

**Comment by MoraliProduktionstechnikGmbH** [comment]
I think you can save the auxiliary space required by the array heights. The following code fragment illustrates the implementation of computeVertexHeight(int, int[], int[]):

```
int computeVertexHeight(int vertex, int [] parent, int[] mem) {

                    if (parent[vertex] == -1)
                            return 1;
                    if (mem[vertex] != 0)
                        return mem[vertex];
                    else
                    {
                        int heightOfVertex = 1 + computeVertexHeight(parent[vertex], parent, mem);
                        mem[vertex] = heightOfVertex;
                        return heightOfVertex;

                    }
        }
```

**Comment by cho-zhang** [comment]
@MoraliProduktionstechnikGmbH OJ stands for Online Judge...AFAIK, the `mem` array you are using is exactly the same as `heights[]` array. Can you explain more on "saving auxiliary space"?
